const productos = [
    {
        id: 1,
        productName: "Pelota champions",
        price: 55000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id: 2,
        productName: "Pelota NBA",
        price: 37000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Basquet"
    },
    {
        id: 3,
        productName: "Pelota Voley",
        price: 27000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Voley",
    },
    {
        id: 4,
        productName: "Pelotas de tenis x3",
        price: 13500,
        quanty: 1,
        img: "./img-products/pelotastenis.png",
        categoria:"Tenis",
    },
    {
        id:5,
        productName: "Remera Adidas Hombre",
        price: 35000,
        quanty: 1,
        img: "./img-products/remera-adidas.jpg",
        categoria:"Futbol",
    },
    {
        id: 6,
        productName: "Pelota champions",
        price: 55000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id: 7,
        productName: "Pelota NBA",
        price: 37000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id: 8,
        productName: "Pelota Voley",
        price: 27000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id: 9,
        productName: "Pelotas de tenis x3",
        price: 13500,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id:10,
        productName: "Remera Adidas Hombre",
        price: 35000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id: 11,
        productName: "Pelota champions",
        price: 55000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id: 12,
        productName: "Pelota NBA",
        price: 37000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id: 13,
        productName: "Pelota Voley",
        price: 27000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id: 14,
        productName: "Pelotas de tenis x3",
        price: 13500,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id:15,
        productName: "Remera Adidas Hombre",
        price: 35000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id: 16,
        productName: "Pelota champions",
        price: 55000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id: 17,
        productName: "Pelota NBA",
        price: 37000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id: 18,
        productName: "Pelota Voley",
        price: 27000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id: 19,
        productName: "Pelotas de tenis x3",
        price: 13500,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id:20,
        productName: "Remera Adidas Hombre",
        price: 35000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id: 21,
        productName: "Pelota champions",
        price: 55000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id: 22,
        productName: "Pelota NBA",
        price: 37000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id: 23,
        productName: "Pelota Voley",
        price: 27000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id: 24,
        productName: "Pelotas de tenis x3",
        price: 13500,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id:25,
        productName: "Remera Adidas Hombre",
        price: 35000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id: 26,
        productName: "Pelota champions",
        price: 55000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    {
        id: 27,
        productName: "Pelota NBA",
        price: 37000,
        quanty: 1,
        img: "./img-products/pelotafutbol.png",
        categoria:"Futbol",
    },
    
];